version: '3.9' # '3.8' ? la terminal indicó que el atributo 'version' es obsoleto, se recomienda removerlo

services:
  postgres:
    image: postgres:15
    container_name: juan_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - juan_net
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: juan_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    networks:
      - juan_net
  
volumes:
  postgres_data:
  
networks:
  juan_net:
    driver: bridge

